name: kmp_ver2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  shimmer: ^2.0.0-nullsafety.0
  image_picker: ^0.8.4+8
  permission_handler: ^10.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  yaml: ^3.1.2

flutter:
  uses-material-design: true
