name: kmp_ver2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependency_overrides:
  path: ^1.8.3
  meta: ^1.9.1
  js: ^0.6.7

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  provider: ^6.0.5
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  connectivity: ^3.0.3
  dio: ^4.0.0-prev2
  shimmer: ^2.0.0-nullsafety.0
  image_picker: ^0.8.4+8
  permission_handler: ^10.0.0
  flutter_screenutil: ^5.7.0
  phone_number: ^1.0.0
  country_code_picker: ^3.0.0
  flutter_camera_overlay: ^0.1.1
  camera: ^0.9.8+1
  pinput: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  yaml: ^3.1.2
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/app/logo.png"

flutter_native_splash:
  color: "#4ec47c"
  image: assets/images/app/logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/app/
    - assets/images/slider/
